name: SlimeLearning
author: NorielSylvire
description: SlimeTweaks adds and changes SF4 recipes to better include 1.18 materials and recylce waste. This is a learning project.
main: me.norielsylvire.slimelearning.SlimeLearning
website: https://github.com/NorielSylvire/SlimeLearning
version: ${project.version}
api-version: 1.18
depend:
- Slimefun
