## CHANGE this to the name of your plugin.
name: SlimeTweaks

## CHANGE this to your username.
author: NorielSylvire

## CHANGE this to a meaninful but short description of your plugin.
description: SlimeTweaks adds and changes SF4 recipes to better include 1.18 materials and recylce waste.

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.NorielSylvire.slimetweaks.SlimeTweaks

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/NorielSylvire/SlimeTweaks

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.18

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun